apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nab-site-com-tls
spec:
  secretName: nab-site-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nab-site.com
  dnsNames:
    - nab-site.com
    - www.nab-site.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - nab-site.com
          - www.nab-site.com